version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: icash
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data
    networks:
      - backend

  purchase-service:
    build: ./purchase-service
    container_name: purchase-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/icash
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - backend

  admin-service:
    build: ./admin-service
    container_name: admin-service
    ports:
      - "8082:8080"
    depends_on:
      - purchase-service
    environment:
      EXTERNAL_BASE_URL: http://purchase-service:8080/api
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
